<MyLayout>
    slide_text: slider_lable
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        
        Label:
            id: slider_lable
            text: "film year"
            font_size: 32
            
        Slider:
            min: 1920
            max: 2022
            step: 1
            orientation: "horizontal"
            on_value: root.slide_it(*args)
            